/**
 * HOLOP Game Constants
 * All numerical constants and game rules.
 * Synced with bot: github.com/VSemenchuk/holop
 */

export const GAME = {
  // Currency caps
  MAX_SILVER: 999_999_999_999,
  MAX_GOLD: 999_999,
  MAX_REPUTATION: 999_999,
  MAX_HEALTH: 100,

  // Starting values
  STARTING_SILVER: 1000,
  STARTING_GOLD: 10,
  STARTING_STARS: 0,

  // Health
  HEALTH_REGEN_PER_MIN: 1,

  // Buildings
  BUILDING_MAX_LEVEL: 15,
  BUILDING_SILVER_MAX_LEVEL: 10,
  INCOME_MAX_HOURS: 24,

  // PvP (synced with bot PVP_CONFIG)
  PVP_UNLOCK_TITLE: 6,
  PVP_COOLDOWN_MINUTES: 5,
  PVP_REVENGE_COOLDOWN_MINUTES: 1,
  PVP_BASE_DAMAGE_MIN: 5,
  PVP_BASE_DAMAGE_MAX: 25,
  PVP_LOOT_PERCENT: 0.08,
  PVP_LOOT_PERCENT_MAX: 0.15,
  PVP_MIN_LOOT: 10,
  PVP_MIN_HEALTH_TO_ATTACK: 20,
  PVP_TITLE_DIFF_LOOT_BONUS: 0.05,
  PVP_DIMINISHING_FACTOR: 0.8,

  // Caves
  CAVE_DARK_UNLOCK_TITLE: 3,
  CAVE_GLORY_UNLOCK_TITLE: 4,
  CAVE_COOLDOWN_EARLY_HOURS: 8,
  CAVE_COOLDOWN_LATE_HOURS: 24,
  CAVE_EARLY_PERIOD_DAYS: 3,

  // Clans
  CLAN_CREATE_COST_SILVER: 25_000,
  CLAN_MIN_TITLE: 7,
  CLAN_MAX_MEMBERS: 50,
  CLAN_INCOME_BONUS: 0.10,

  // Items
  IRON_DOME_DURATION_HOURS: 24,
  DYNAMITE_DURATION_HOURS: 24,

  // Serfs
  SERF_COLLECTION_INTERVAL_MIN: 30,
  SERF_MAX_ACCUMULATION_HOURS: 8,
  SERF_FREEDOM_BONUS: 0.15,

  // Daily Bonus
  DAILY_BONUS_CYCLE_DAYS: 14,
  DAILY_MAX_STREAK: 14,
  DAILY_MASTER_BONUS_SILVER: 200,
  DAILY_COOLDOWN_HOURS: 24,
  DAILY_GRACE_HOURS: 48,
  DAILY_FREEZE_HOURS: 72,
  DAILY_ROLLBACK_DAYS: 3,
  DAILY_RESTORE_COST_STARS: 2,
  DAILY_RESTORE_MAX_DAYS: 3,

  // Serf Capture
  SERF_SLOT_COST_STARS: 100,
  SERF_MAX_SLOTS: 30,
  SERF_BASE_SLOTS: 2,
  SERF_PROFESSION_CHOICE_COST_STARS: 10,
  SERF_MIN_HOURS_TRANSFER: 8,

  // Serf Ransom
  SERF_RANSOM_OWNER_SHARE: 0.70,
  SERF_RANSOM_BASE_MULTIPLIER: 6,
  SERF_RANSOM_TIME_BONUS_PER_DAY: 0.10,
  SERF_RANSOM_TIME_BONUS_MAX: 1.0,
  SERF_RANSOM_MIN_PRICE: 500,
  SERF_RANSOM_GOLD_THRESHOLD: 15000,
  SERF_RANSOM_STARS_THRESHOLD: 100000,
  SERF_SILVER_TO_GOLD: 100,
  SERF_SILVER_TO_STARS: 2000,

  // Frog Potion
  FROG_POTION_COST_STARS: 5, // Synced with bot POTIONS.frog_potion.stars_price

  // Combat
  COMBAT_BASE_ATTACK: 10,
  COMBAT_ATTACK_PER_LEVEL: 2,
  COMBAT_BASE_DEFENSE: 10,
  COMBAT_DEFENSE_PER_LEVEL: 2,

  // Defenses
  IRON_DOME_COST_STARS: 25,
  STONE_WALL_COST_STARS: 50,
  TREBUCHET_COST_STARS: 25,
  POWDER_KEG_COST_STARS: 100,
  POWDER_KEG_DURATION_HOURS: 24,
  BLESSING_COST_STARS: 150,
  INVISIBILITY_COST_STARS: 300,
  INVISIBILITY_DURATION_HOURS: 48,

  // Healing
  LIFE_ELIXIR_COST_GOLD: 50,

  // Bank
  BANK_UNLOCK_COST_STARS: 499,
  BANK_INTEREST_RATE_PER_DAY: 0.10,
  BANK_MAX_DEPOSIT_HOURS: 24,
  BANK_MIN_DEPOSIT: 100,
  BANK_MAX_INTEREST_PER_DAY: 10000,

  // Cave
  CAVE_RESURRECTION_BASE_STARS: 10,
  CAVE_RESURRECTION_PER_LEVEL_STARS: 5,

  // Idle loop
  INCOME_TICK_INTERVAL_MS: 1000,
} as const;

export type GameConstants = typeof GAME;
