/**
 * HOLOP Game Constants
 * All numerical constants and game rules.
 */

export const GAME = {
  // Currency caps
  MAX_SILVER: 999_999_999_999,
  MAX_GOLD: 999_999,
  MAX_REPUTATION: 999_999,
  MAX_HEALTH: 100,

  // Starting values
  STARTING_SILVER: 1000,
  STARTING_GOLD: 10,
  STARTING_STARS: 0,

  // Health
  HEALTH_REGEN_PER_MIN: 1,

  // Buildings
  BUILDING_MAX_LEVEL: 15,
  BUILDING_SILVER_MAX_LEVEL: 10,
  BUILDING_UPGRADE_COOLDOWN_MIN: 30,
  DEFAULT_COST_MULTIPLIER: 1.9,
  DEFAULT_INCOME_MULTIPLIER: 1.5,

  // PvP
  PVP_UNLOCK_TITLE: 6,
  PVP_COOLDOWN_MIN: 1,
  PVP_COOLDOWN_MAX: 5,
  PVP_BASE_DAMAGE_MIN: 20,
  PVP_BASE_DAMAGE_MAX: 40,
  PVP_LOOT_PERCENT: 0.30,
  PVP_ROBIN_HOOD_PERCENT: 0.05,

  // Caves
  CAVE_DARK_UNLOCK_TITLE: 3,
  CAVE_GLORY_UNLOCK_TITLE: 4,
  CAVE_COOLDOWN_EARLY_HOURS: 8,
  CAVE_COOLDOWN_LATE_HOURS: 24,
  CAVE_EARLY_PERIOD_DAYS: 3,

  // Clans
  CLAN_CREATE_COST_SILVER: 25_000,
  CLAN_MIN_TITLE: 7,
  CLAN_MAX_MEMBERS: 50,
  CLAN_INCOME_BONUS: 0.10,

  // Items
  IRON_DOME_DURATION_HOURS: 24,
  DYNAMITE_DURATION_HOURS: 24,

  // Serfs
  SERF_COLLECTION_INTERVAL_MIN: 30,

  // Daily Bonus
  DAILY_BONUS_CYCLE_DAYS: 14,

  // Idle loop
  INCOME_TICK_INTERVAL_MS: 1000, // Update silver every second
} as const;

export type GameConstants = typeof GAME;
